title: 'Norad : urbex et mouvement urbain'
baseurl: /
permalink: '/:title/'
layout_style: grid
palette: blue
header:
  type: header
  title: Norad.
  logo_img: images/logo.svg
  logo_img_alt: Ampersand Logo
  has_nav: true
  nav_links:
    - type: action
      label: Home
      url: /
      style: link
    - type: action
      label: About
      url: /about
      style: link
    - type: action
      label: Style Guide
      url: /style-guide
      style: link
    - type: action
      label: Contact
      url: /contact
      style: link
footer:
  type: footer
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=ampersand&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>.
  has_social: true
  social_links:
    - type: action
      label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: twitter
      new_window: true
    - type: action
      label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: instagram
      new_window: true
    - type: action
      label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: github
      new_window: true
    - type: action
      label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: linkedin
      new_window: true
    - type: action
      label: DEV
      url: 'https://dev.to/'
      style: icon
      icon_class: dev
      new_window: true
  has_subscribe: true
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
    Subscribe to my email newsletter to receive useful articles and special
    offers. This monthly email is sent out on the first of every month.
  subscribe_action: /subscribe-success
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
collections:
  posts:
    permalink: '/posts/:title/'
domain: 'https://norad-be850.netlify.app'
favicon: /images/c566d9b74a377523a27419b4af6cec5e.png
